services:
  server:
    image: server
    build: server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - PORT=${SERVER_PORT}

  frontend:
    image: frontend
    build: frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - PORT=${FRONTEND_PORT}

  bot1:
    image: bot1
    build: "bots/godlikerainer"
    environment:
      - SERVER_URL=http://server:${SERVER_PORT}
    depends_on:
      - server

  bot2:
    image: bot2
    build: "bots/rainer"
    environment:
      - SERVER_URL=http://server:${SERVER_PORT}
    depends_on:
      - server